### ISSUE TITLE
Latest core changes affected all assemblies with smite

### ISSUE THREAD

**Issue by MissSecret** [LeagueSharp/LeagueSharpCommon#154]
Error compiling

Black Warwick
Master yi by prunes
Roach_'s pantheon
FALeesin
Metasmite
J_utity
Oracle
Diabeths assemblies

**Comment by trees-software** [comment]
1.) This isn't the LeagueSharp Core repo.
2.) The change were reported almost 2 weeks ago [here](http://www.joduska.me/forum/topic/12669-important-api-changes-421/)
3.) We aren't responsible for developers not updating their assemblies.
